# Generated by Django 5.0.2 on 2024-03-07 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sourse',
            new_name='Source',
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name_plural': 'Sources'},
        ),
        migrations.RenameField(
            model_name='income',
            old_name='sourse',
            new_name='source',
        ),
    ]
