# Generated by Django 5.0.2 on 2024-03-18 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_source_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='user',
        ),
    ]
