# Generated by Django 5.0.2 on 2024-03-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0002_rename_curreny_userpreferences_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='currency',
            field=models.CharField(blank=True, default='USD -- United States Dollar', max_length=255, null=True),
        ),
    ]
